### ISSUE TITLE
bCNC communication

### ISSUE THREAD

**Issue by vlachoudis** [lordmundi/shuttleCP#5]
Hi, @chamnit mentioned that you would like to connect your shuttleXpress jogging program with bCNC. I would be happy to help, or provide from the bCNC what is need.
Could you explain me the communication protocol.

Cheers
Vasilis

**Comment by lordmundi** [comment]
sure... this issue is probably a better place for this communication
anyways... i'll repost here:

i'd be interested in helping.  What shuttleCP is sending out is not written
in stone - it is writing to a websocket that the Chilipeppr Serial Port
JSON Server uses.  If bCNC isn't using websockets, they could be added to
bCNC to be compatible with what SPJS is getting (John has SPJS documented
pretty well on the github page).  But, if you aren't going to use
websockets, and shuttleCP will have to change anyway, you could change
shuttleCP to send something simpler to bCNC ( a regular socket perhaps, or
a REST api, whatever is best ).  libcurl could be added in to support REST
if that is the way you want to go.  Or, you could do something much lighter
weight then going all the way up to http... like a simple udp socket...

FG

On Fri, May 8, 2015 at 1:06 PM, Vasilis Vlachoudis <notifications@github.com

**Comment by lordmundi** [comment]
and the SPJS is documented on the github page here... like I said, all
websocket based:  https://github.com/johnlauer/serial-port-json-server

**Comment by vlachoudis** [comment]
I don't use SPJS but i have already a web server for the web pendant. For the moment it can accept any gcode or any bCNC command and can return in json the grbl status. As for any web server the communication doesn't stay on, it is just a request and you get back a result

**Comment by lordmundi** [comment]
yes, exactly.  so, a switch could be made in shuttleCP to switch between
SPJS websocket or bCNC web commands.  Right now I don't read any feedback,
so you could just send the commands out using libcurl.

FG

On Fri, May 8, 2015 at 3:47 PM, Vasilis Vlachoudis <notifications@github.com

**Comment by vlachoudis** [comment]
I've downloaded your program and I will check what you need for the communication.

**Comment by lordmundi** [comment]
Look into libcurl. It is probably the easiest way to talk http in C.

FG

**Comment by vlachoudis** [comment]
Once you start the pendant in bCNC you can send you
gcodes instead of the websocket as 
http://localhost:8080      (port defined in the init of bCNC)
with one GET per line e.g.
GET /send?gcode=G90G0X1

**Comment by lordmundi** [comment]
Ok. That might do it. It might be good to allow multiple line submissions
in one GET though so there isn't all the overhead to switch between G90 and
G91. For example, if I could put a semicolon between them or some character
that isn't normally in gcode and you could treat it as a newline.

FG

**Comment by vlachoudis** [comment]
Thats a good idea. Semicolon could work and I can split it into multiple lines.

**Comment by vlachoudis** [comment]
Ok done. You have to checkout the latest version from the repository. I've added so a multiple command should be like
send?gcode=line1%3Bline2%3Bline3 ...
%3B = uri encoded ;

**Comment by lordmundi** [comment]
awesome.  however... i just did a quick search and found this(
https://github.com/synthetos/TinyG/wiki/Gcode-Support ) which says that
semicolon can also be used to start a comment.  This change would be bad in
that case since it would cause code meant to be commented out to be run as
a new statement.

could we change it to something like a uri encoded carriage return (%0D)
instead?  this would get away from that case and fix it before anyone
starts using it.  also, it kinda seems consistent with what we are trying
to do.

FG

**Comment by vlachoudis** [comment]
Yes no problem I will change. Normally I am filtering the comments before sending to grbl, but the pendant commands are executed unfiltered

**Comment by vlachoudis** [comment]
For some strange reason the BaseHTTPD server of python doesn't like the %0D. I've put the %0A which is the \n for linux

**Comment by lordmundi** [comment]
Sounds good. Hopefully I'll get some time to try putting this into
shuttleCP, but I've got a few other projects going on that I have to
finish. Anyone feel free to put this into shuttleCP and send me a pull
request.

FG
