### ISSUE TITLE
How can i deactivate wiringPi?

### ISSUE THREAD

**Issue by xpix** [lordmundi/shuttleCP#7]
I like your module very much, but if i want to use the GPIO's with another program. How can i deactivate the wiringPi support?

**Comment by lordmundi** [comment]
Ok, so I made an attempt at adding this capability this morning, but I don't have any way to test it since my raspi is not available right now.  So, I put it in a separate branch called "gpio_disable".  Checkout to this branch and edit the Makefile to change "GPIO_SUPPORT" to 0.  Hopefully that will work for you.  If it does, please post back here and I will merge it into the main master branch.

**Comment by xpix** [comment]
Compile, but i don't know if works:

```
root@raspb-b2:~/shuttleCP# make
cc -O3 -W -Wall -I /usr/local/include/nopoll -DGPIO_SUPPORT=0   -c -o shuttlecp.o shuttlecp.c
cc -O3 -W -Wall -I /usr/local/include/nopoll -DGPIO_SUPPORT=0   -c -o websocket.o websocket.c
cc -O3 -W -Wall -I /usr/local/include/nopoll -DGPIO_SUPPORT=0   -c -o led_control.o led_control.c
cc -O3 -W -Wall -I /usr/local/include/nopoll -DGPIO_SUPPORT=0   -c -o raspi_switches.o raspi_switches.c
gcc -O3 -W -Wall -I /usr/local/include/nopoll -DGPIO_SUPPORT=0 shuttlecp.o websocket.o led_control.o raspi_switches.o -o shuttlecp -lwiringPi -lnopoll -Wl,-rpath -Wl,/usr/local/lib

root@raspb-b2:~/shuttleCP# ./shuttle
Starting shuttleCP ...
sudo: unable to resolve host raspb-b2
Attempting connection to localhost:8989
Websocket connected.
/dev/input/by-id/usb-Contour_Design_ShuttleXpress-event-if00: No such file or directory
/dev/input/by-id/usb-Contour_Design_ShuttleXpress-event-if00: No such file or directory
```

**Comment by lordmundi** [comment]
Ok, sounds like it isn't seeing your shuttle hardware. Once you resolve
that, let me know if it works as normal.

FG
